import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./_components/navigation";
import { Analytics } from "@vercel/analytics/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="max-w-md mx-auto p-4 h-[100vh]">
          <div>
            {children}
            <Analytics />
          </div>
          <div className="pb-1 pt-4">
            <Navigation />
          </div>
        </main>
      </body>
    </html>
  );
}
